variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker ps -a

