image: tmaier/docker-compose:latest

stages:
  - build
  - test

services:
  - docker:dind

build:
  stage: build
  before_script:
    - docker info
    - docker-compose version
  script:
    - docker-compose -f docker-compose.yml build --no-cache
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose-test.yml build --no-cache

test:
  stage: test
  script:
    - docker-compose -f docker-compose-test.yml run --rm tests

cleanup:
  stage: .post
  script:
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose-test.yml down
  when: always
