image: tmaier/docker-compose:19.03

stages:
  - test
  #- build

services:
  - docker:dind

test:
  stage: test
  before_script:
    - docker-compose -f docker-compose-test.yml -p ci_test build --no-cache
    - docker-compose -f docker-compose-test.yml -p ci_test up -d rabbitmq orig imed obse httpserv api-gateway
    - sleep 20 # Wait for some messages to be registered
  script:
    - docker-compose -f docker-compose-test.yml -p ci_test run --rm tests

#build:
  #stage: build
  # script:
    # - docker-compose -f docker-compose.yml build --no-cache
    # - docker-compose -f docker-compose.yml up -d

cleanup:
  stage: .post
  script:
    # - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose-test.yml -p ci_test down
  when: always
