image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker ps -a

