image: tmaier/docker-compose:19.03

stages:
  - test
  - build
  - deploy

services:
  - docker:dind

test:
  stage: test
  before_script:
    - docker-compose -f docker-compose-test.yml -p ci_test build --no-cache
    - docker-compose -f docker-compose-test.yml -p ci_test up -d rabbitmq orig imed obse httpserv api-gateway
    - sleep 30 # Wait for services to start and some messages to be registered
  script:
    - docker-compose -f docker-compose-test.yml -p ci_test run --rm tests
  after_script:
    - docker-compose -f docker-compose-test.yml -p ci_test down

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build --no-cache

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
