image: docker:latest

services:
  - hmajid2301/dind-docker-compose

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose version
    - docker ps -a

