image: docker/compose:latest

services:
  - docker:dind

before_script:
  - export DOCKER_HOST="${HOSTNAME}-docker"
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker ps -a

