image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  image: hmajid2301/dind-docker-compose
  script:
    - docker-compose version
    - docker ps -a

