version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - "5672"
    ports:
      - "15672:15672"
    networks:
      - mq-network
      
  orig:
    depends_on:
      - "rabbitmq"
    command: ["/original/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./original
      network: host
    expose:
      - "5000"
    networks:
      - mq-network

  imed:
    depends_on:
      - "rabbitmq"
    command: ["/intermediate/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "app.js"]
    build:
      dockerfile: Dockerfile
      context: ./intermediate
      network: host
    networks:
      - mq-network

  obse:
    depends_on:
      - "rabbitmq"
    command: ["/observer/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "app.js"]
    build:
      dockerfile: Dockerfile
      context: ./observer
      network: host
    networks:
      - mq-network
    volumes:
      - ./message-store:/var/lib/messages

  httpserv:
    command: ["node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./http-service
      network: host
    ports:
      - "8082:8082"
    networks:
      - mq-network
    volumes:
      - ./message-store:/var/lib/messages

  api-gateway:
    depends_on: 
      - "httpserv"
    command: ["node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
      network: host
    ports:
      - "8081:8081"
    networks:
      - mq-network
    volumes:
      - ./message-store:/var/lib/messages

networks:
  mq-network:
    external: 
      name: gitlab-network
    driver: "bridge"

volumes:
  message-store:
