version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - "5672"
    networks:
      - test-network
      
  orig:
    depends_on:
      - "rabbitmq"
    command: ["/original/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./original
      network: host
    networks:
      - test-network

  imed:
    depends_on:
      - "rabbitmq"
    command: ["/intermediate/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "app.js"]
    build:
      dockerfile: Dockerfile
      context: ./intermediate
      network: host
    networks:
      - test-network

  obse:
    depends_on:
      - "rabbitmq"
    command: ["/observer/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "app.js"]
    build:
      dockerfile: Dockerfile
      context: ./observer
      network: host
    networks:
      - test-network
    volumes:
      - ./test-message-store:/var/lib/messages

  httpserv:
    command: ["node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./http-service
      network: host
    networks:
      - test-network
    volumes:
        - ./test-message-store:/var/lib/messages

  api-gateway:
    depends_on: 
      - "httpserv"
    command: ["node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
      network: host
    networks:
      - test-network

  tests:
    depends_on: 
      - "api-gateway"
    command: ["npm", "run", "test" ]
    build:
      dockerfile: Dockerfile.tests
      context: .
      network: host
    volumes:
      - ./test-message-store:/var/lib/messages
    networks:
      - test-network

volumes:
  test-message-store:

networks: 
  test-network: