version: "3"

services:
  tests:
    command: ["npm", "run", "test" ]
    build:
      dockerfile: Dockerfile.tests
      context: .
    volumes:
      - ./message-store:/var/lib/messages

volumes:
  message-store: