version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-test
    expose:
      - "5672"
    networks:
      - test-network
      
  orig:
    depends_on:
      - "rabbitmq"
    command: ["/original/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./original
      network: host
    container_name: orig-test
    networks:
      - test-network

  imed:
    depends_on:
      - "rabbitmq"
    command: ["/intermediate/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "app.js"]
    build:
      dockerfile: Dockerfile
      context: ./intermediate
      network: host
    container_name: imed-test
    networks:
      - test-network

  obse:
    depends_on:
      - "rabbitmq"
    command: ["/observer/utils/wait-for-it.sh", "rabbitmq:5672", "-t", "30", "-s", "--", "node", "app.js"]
    build:
      dockerfile: Dockerfile
      context: ./observer
      network: host
    container_name: obse-test
    networks:
      - test-network
    volumes:
      - ./test-message-store:/var/lib/messages

  httpserv:
    depends_on:
      - "obse"
    command: ["node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./http-service
      network: host
    container_name: httpserv-test
    networks:
      - test-network
    volumes:
        - ./test-message-store:/var/lib/messages

  api-gateway:
    depends_on: 
      - "httpserv"
    command: ["node", "start.js"]
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
      network: host
    container_name: api-gateway-test
    environment: 
      - NODE_ENV=test
    networks:
      - test-network
    volumes:
      - ./test-message-store:/var/lib/messages
      # Docker socket to run docker commands from inside the container
      - //var/run/docker.sock:/var/run/docker.sock

  tests:
    depends_on: 
      - "api-gateway"
    command: ["npm", "run", "test" ]
    build:
      dockerfile: Dockerfile.tests
      context: .
      network: host
    container_name: tests
    networks:
      - test-network
    volumes:
      - ./test-message-store:/var/lib/messages
      # Docker socket to run docker commands from inside the container
      - //var/run/docker.sock:/var/run/docker.sock


volumes:
  test-message-store:

networks: 
  test-network: